<%@ Page Language="C#" AutoEventWireup="true" CodeFile="InlineUpdate_Delete.aspx.cs" Inherits="InlineUpdate_Delete" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <center>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="empid" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="empid" HeaderText="empid" ReadOnly="True" SortExpression="empid" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Addr" HeaderText="Addr" SortExpression="Addr" />
                <asp:BoundField DataField="Phno" HeaderText="Phno" SortExpression="Phno" />
                <asp:BoundField DataField="Sal" HeaderText="Sal" SortExpression="Sal" />
                <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                <asp:BoundField DataField="Gen" HeaderText="Gen" SortExpression="Gen" />
                <asp:BoundField DataField="Dep" HeaderText="Dep" SortExpression="Dep" />
                <asp:BoundField DataField="Cmp" HeaderText="Cmp" SortExpression="Cmp" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:OfficeConnectionString %>" SelectCommand="SELECT * FROM [EmployeeDetails]" UpdateCommand="update [EmployeeDetails] set [Name]=@Name,[Addr]=@Addr,[Phno]=@Phno,[Sal]=@Sal,[City]=@City,[Gen]=@Gen,[Dep]=@Dep,[Cmp]=@Cmp where [empid]=@empid" DeleteCommand="delete from [EmployeeDetails] where [empid]=@empid"></asp:SqlDataSource>
    </center>
    </div>
    </form>
</body>
</html>
